#include<iostream>
using namespace std;
main(){
       int A,B,C,D,E,F,G,H,I,J,K,L,M,N,O;
       int add,multiply,subtract;
       int adds;
       int subs;
       cout << "Number 1: ";
       cin >> A;
       cout << "Number 2: ";
       cin >> B;
       cout << "Number 3: ";
       cin >> C;
       cout << "Number 4: ";
       cin >> D;
       cout << "Number 5: ";
       cin >> E;
       cout << "Number 6: ";
       cin >> F;
       cout << "Number 7: ";
       cin >> G;
       cout << "Number 8: ";
       cin >> H;
       cout << "Number 9: ";
       cin >> I;
       cout << "Number 10: ";
       cin >> J;
       cout << "Number 11: ";
       cin >> K;
       cout << "Number 12: ";
       cin >> L;
       cout << "Number 13: ";
       cin >> M;
       cout << "Number 14: ";
       cin >> N;
       cout << "Number 15: ";
       cin >> O;
       add = A+B+C+D+E;
       multiply = F*G*H*I*J;
       subtract = K-L-M-N-O;
       adds = add+multiply;
       subs = adds-subtract;
       cout << "The final result is: "<<subs;
}
